### ISSUE TITLE
add ClaimResponse to schema

### ISSUE THREAD

**Issue by num46664** [rialtic-community/insight-engine-schema-python#4]
We need to add the Claim Response object to our InsightEngineRequest Schema.

Bharath may be working on this, but it also may be an abandoned task. Lets follow up with him and take this on if needed

This is required for some of the engines in queue (D&B).

**Comment by daniel-ufabc** [comment]
ClaimResponse comes in Claim.insurance>Insirance.claimResponse, therefore it is stored inside Claim.resources. Closing.
